title: Thomas Joulin
email: thomas@joulin.eu
description: ""
url: "https://blog.thomas.joulin.eu"
twitter_username: thomasjoulin
github_username:  thomasjoulin
paginate: 10
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
